name: 🐛 模板错判上报 (Template Bug)
description: 上报你在模板规则中发现的错误 (Bug report for template rules)
title: '[模板错误] 简要描述问题'
labels: ["bug"]

body:
  - type: checkboxes
    id: verify_steps
    attributes:
      label: 前置确认 (Pre-check)
      description: 提交前请确认以下事项，以减少无效沟通：
      options:
        - label: 我已在 [Issue Tracker](https://github.com/heunghingwan/Aethersailor-Custom_OpenClash_Rules/issues) 中搜索过类似问题
          required: true
        - label: "**我确认这确实是本项目模板文件导致的规则分流错误**"
          required: true
        - label: 我使用的是 OpenWrt/ImmortalWrt 官方固件或官方 ImageBuilder，非第三方修改版
          required: true
        - label: 我使用的是最新版本的 OpenClash 和核心
          required: true
        - label: 我已阅读 [Wiki 故障排除](https://github.com/heunghingwan/Aethersailor-Custom_OpenClash_Rules/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4) 章节但未能解决
          required: true

  - type: input
    id: openclash_version
    attributes:
      label: OpenClash Version
      description: 例如：v0.45.169-beta
      placeholder: "v0.0.0-beta"
    validations:
      required: true

  - type: dropdown
    id: bug_ini
    attributes:
      label: 涉及的模板文件 (Problematic File)
      description: 发现问题所在的模板
      multiple: true
      options:
        - Custom_Clash.ini
        - Custom_Clash_Full.ini
        - Custom_Clash_GFW.ini
        - Custom_Clash_Lite.ini
        - Custom_Clash_Mainland.ini
    validations:
      required: true

  - type: textarea
    id: describe_bug
    attributes:
      label: Bug 描述 (Description)
      description: 请清晰描述规则错误的行为。例如：“域名 exmaple.com 应该走代理，但被直连了”。
    validations:
      required: true

  - type: textarea
    id: describe_phenomenon
    attributes:
      label: 故障复现 (Reproduction)
      description: 描述如何复现该问题，或提供相关的日志片段。
    validations:
      required: true

  - type: textarea
    id: describe_solution
    attributes:
      label: 建议修复方案 (Optional)
      description: 如果你知道如何修复此问题，请提供建议。
    validations:
      required: false
